### ISSUE TITLE
An error occurred while scanning the local system.

### ISSUE THREAD

**Issue by MonstersInc-sudo** [ipsingh06/seedsync#113]
Can't change local directory to anything but "downloads".

**Comment by MonstersInc-sudo** [comment]
Issue is with permissions on local server, not with codebase.

**Comment by jandreaucodes** [comment]
Were you able to get this sorted out?

I gave Docker permission to the directory I'm trying to download to, but I'm still getting this error.

**Comment by MonstersInc-sudo** [comment]
> Were you able to get this sorted out?
> 
> I gave Docker permission to the directory I'm trying to download to, but I'm still getting this error.

Yeah I was able to sort it out.

I am going to assume you are using Docker on Synology.

When configuring the container there is a tab called "Volume".

I had to make sure the "Mount path" was something named "downloads", so it matched the Seedsync default settings. 

In my example the File/Folder was pointed to "docker/Seedsync" with the mount path of "/downloads".

That seemed to solve the issue for me. I can upload screenshots later this week if the above doesn't help you.

Ultimately though, I think there is an issue with the codebase that when you specify a path on the Seedsync GUI for remote path it doesn't switch it over. I was going to do a pull request and look into it, but haven't had time yet.

**Comment by cypekis11** [comment]
Hi,

I also have ds920+ and cannot install seedsync with docker.

Installing with scheduler result with:

![IMG_20220504_162553](https://user-images.githubusercontent.com/28142237/166702974-9f78dca4-5d64-4f15-9829-96e01c2ba370.jpg)

Installing with existing docker register package does install and work, but won't access the downloads and config folders. It manages to connect and even starts mirroring, but the files won't appear in any visible volume1 folder. Like as if it installs somewhere in root, which is not accessible. 

Changing the Mount Path to 'downloads' results with crashing container - it won't start anymore. 

Edit:
Seems the issue is not only by me. 
https://github.com/ipsingh06/seedsync/issues/86

Any solution?
