### ISSUE TITLE
Not Found Error

### ISSUE THREAD

**Issue by GeorgeMeli** [ipsingh06/seedsync#131]
I am new to Docker and Seedsync. I have done everything mentioned on the installation page to install Docker and Seedsync as well. Everything seems to be working and I can open the webui in the browser and also download files from the seedbox. But those files stay in the downloads folder in the container. 

I cannot add local directory using the commands mentioned on that page. I used the commands in the container terminal and keep getting /bin/sh: 1:  docker: not found. Cannot figure it out even after 5-6 hours of Googling.

**Comment by quadcom** [comment]
How are you spinning up the Docker container? NAS? bare metal? Unraid?

**Comment by GeorgeMeli** [comment]
Installed Docker Desktop on my Windows 11 PC and ran the container from there.

**Comment by quadcom** [comment]
can you post your Docker command that spun up the container?

**Comment by GeorgeMeli** [comment]
I was running the docker run commands inside the container itself, may be that was the problem. 
I ran the commands through powershell from the resources\bin folder in program files of docker and they ran correctly and the files are now being copied to local folder as intended.

Thank you for your time

**Comment by quadcom** [comment]
So Docker Desktop on Windows is not something I am familiar with.

But the basics with Docker are you need a volume to store persistent data. Everytime you update the image (version of the app) without a volume that holds the persistent data, your configuration would be wiped out. 

The concept of a volume is a folder on the host system (Windows 11) that would be accessible from directly within the container (Seedsync)

The Docker docs that refer to volumes is here 

(https://docs.docker.com/storage/volumes/)

It looks like there is a section in Docker Desktop to configure all of your volumes. You then can inspect the Seedsync container and in that config is where you would connect a volume to the container.

I found this YT vid that looks like it might explain it.

https://www.youtube.com/watch?v=ex4XMet78q8&pp=ygUWZG9ja2VyIGRlc2t0b3Agdm9sdW1lcw%3D%3D

**Comment by GeorgeMeli** [comment]
I opened powershell into this folder C:\Program Files\Docker\Docker\resources\bin and then ran this docker run command for local directory 
docker run \
   -p 8800:8800 \
   -v <downloads directory>:/downloads \
   -v <config directory>:/config \
   ipsingh06/seedsync

Now it is correctly copying the file to the local directory instead of the container itself.

**Comment by quadcom** [comment]
So the "-v :/downloads" and "-v :/config" are the volume mapping. 

The way it works is put the path where you want in the host system before the colon. That would then be mapped to the DIR inside the container which is defined after the colon.

The following would map "d:\downloads" into the DIR "/downloads" inside the container. 

-v "d:\downloads":/downloads

If you were to pull up the console for the container and look in the /downloads DIR, you would actually be looking at the contents of "d:\downloads"

Same thing would apply to the config DIR. That is where the Seedsync configurations files are stored. They are stored outside of the container because updating the image would wipe the existing container contents causing Seedsync to have no config.

Think of it like a Windows shortcut but it's more like a Linux symbolic link (which Windows also has but that's another story).

Since you have nothing before the colon currently, Docker is simply mapping that local DIR to both /downloads and /config. That's not really the best situation. If you want to keep them in that parent folder but at least keep downloads and configs separate, you could edit those to the following.

-v \downloads:/downloads
-v \config:/config

**Comment by GeorgeMeli** [comment]
Thank you, that is what I did, just forgot to add that part in the above comment. I was running the commands in the wrong terminal. The Exec terminal in the container itself. I had to run it from docker folder from Program files as I pointed above. Thank you for helping.
