### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/config/settings.cfg'

### ISSUE THREAD

**Issue by jamauai** [ipsingh06/seedsync#88]
Still getting this error with the latest Docker image. Tried both Docker UI and manually via CLI. 

`PermissionError: [Errno 13] Permission denied: '/config/settings.cfg'`

![5F0F12E9-7D2A-4F52-8B7F-F8CE339B1336](https://user-images.githubusercontent.com/16515595/107146337-a0d74d80-68eb-11eb-819d-267b8813644b.png)

**Comment by ipsingh06** [comment]
@jamauai By default SeedSync runs as the non-privileged user 1000 in the docker container. If your settings are owned by a different user, then you will get these permission errors. You need to use the `--user` argument in `docker run` to run as a different user. See https://ipsingh06.github.io/seedsync/install/#docker-image-linuxubuntu-raspberry-pi as well.

**Comment by jamauai** [comment]
Will run another test and report back. I have the user defined in Docker UI yet still get the permissions error. Forgot to include "user" when testing CLI.

**Comment by jamauai** [comment]
That worked, thank you. Here's what I ran:

`sudo docker run -p 8800:8800 -v /volume1/docker/seedsync:/config -u 1032:100 ipsingh06/seedsync`

For my own reference, defining the user via the Docker app UI did **NOT** work:

![Screen Shot 2021-02-12 at 1 28 30 AM](https://user-images.githubusercontent.com/16515595/107763743-2afc2900-6cd3-11eb-933e-9c89265f360c.png)

**Comment by quadcom** [comment]
You've missed the mapping for the incoming folder. I also don't think you would want to store the config files directly in the folder you defined. You might want to have them in a config folder all safe and such.

Since your running Docker on Synology, run this but change the vars to match what you are using.


sudo docker run --name SeedSync -p 8802:8800 -v /volume3/Sync/Seedbox/z-config:/config -v /volume3/Sync/Seedbox/1-Incoming:/incoming --user 1039:65539 ipsingh06/seedsync:latest

You may need to also include a lang definition in the container settings once the container is built. This would depend on which lang your seedbox server is set to.

There are a couple of threads from users here that are running Docker on Synology. It's a little different beast than vanilla Docker and needs some tweaking.
