### ISSUE TITLE
Synology/Docker - Inherited permissions being stripped from downloaded files and folders

### ISSUE THREAD

**Issue by jamauai** [ipsingh06/seedsync#91]
I'm currently on v0.8.6. and still seeing post-download permission issues similar to this:

https://github.com/ipsingh06/seedsync/issues/50#issuecomment-630269510

Permissions are fine during download, but once the download is complete, all permissions are stripped except the user specified when the Docker container was created. This is a problem for me as I have each Docker app running as a different user (Radarr, Sonarr, etc.). Rather than modify all the other apps to use the same account, I would rather SeedSync stop stripping permissions.

This is what the file/folder permissions look like _during_ download:
![Screen Shot 2021-03-06 at 1 33 18 AM](https://user-images.githubusercontent.com/16515595/110206165-3816be80-7e20-11eb-8bce-e19520398037.png)

This is what the permissions look like once download is complete:
![Screen Shot 2021-03-06 at 1 36 25 AM](https://user-images.githubusercontent.com/16515595/110206178-48c73480-7e20-11eb-92c4-b2c826e564c0.png)

**Comment by quadcom** [comment]
In all honesty, I think it's Synology's implementation of Docker.

I used to use SS in a Docker container in my DS1515+ and I moved off to  SS running on Debian in a VM on an ESXi install. Much easier to get up and running quickly and I have full control over user accounts that SS runs under; which happens to be the same user account on my NAS. I've had ZERO issues since moving over.

My advice, while Docker is neat and the Synology NAS products are awesome. I'd look into building a VM hypervisor out of some older hardware. It'll do a couple of things for you. If you aren't that Linux savvy (like me definitely) you'll learn a bit more about Linux and how to get around. and Two, Seedsync will run like an animal and you'll never have any issues. OK, a third thing it'll do, expose you to all sorts of other systems you can get running in a VM like PiHole for your whole network. 

It's a deep rabbit hole but it's a lot of fun when it's all up and running.

**Comment by jamauai** [comment]
I'm sure this is something @ipsingh06 can fix.

**Comment by absywabsy** [comment]
I have just spent about 5 hours trying to figure out this problem before coming here...thank GOD someone is also facing this problem.

I agree, I am getting this problem myself. Please can you make it so Seedsync doesn't just apply it's own permissions to the files moved over onto the Synology and use the Synology parent folder of where the files are saved to provide the permissions?

**Comment by quadcom** [comment]
Can both of you share your Docker run command so we can see how your starting SS?

**Comment by absywabsy** [comment]
> Can both of you share your Docker run command so we can see how your starting SS?

Hi, I used the command from your post at the bottom of this page when **first setting it up** in Synology Docker:

https://www.gitmemory.com/issue/ipsingh06/seedsync/53/637796960

But ever since then, if it turns off for whatever reason, I go back into my docker app on my Synology and turn it back on just by pressing the button

**Comment by quadcom** [comment]
So you got the UID and GID from an SSH session on the NAS for an account on the NAS that has full access to the folders you want to access from inside the container?

**Comment by absywabsy** [comment]
> So you got the UID and GID from an SSH session on the NAS for an account on the NAS that has full access to the folders you want to access from inside the container?

Yep that's exactly what I did

**Comment by absywabsy** [comment]
I have since moved to unRAID and I no longer receive this issue, my script can freely delete the files leftover by seedsync without worrying about permissions getting in the way of the deletion.

**Comment by quadcom** [comment]
As I suggested, Synology's implementation of Docker is sketchy.

**Comment by ipsingh06** [comment]
Hey folks, apologies for the delayed response here. Glad you were able to reach a solution, @absywabsy .
For reference for any folks reading this in the future, the best way to control the user and group under which the SeedSync image runs is via the `docker run` flags `--user <uid>:<gid>`, as outlined in the [documentation](https://ipsingh06.github.io/seedsync/install/). If using any frontend to run docker images, you'll have to make sure their user/group settings map to this flag. Cheers.
